FALSE = '0'
TRUE = '1'

LOGIN_SCREEN = 'LOGIN'
MENU_SCREEN = 'MENU'
SIGNUP_SCREEN = 'SIGNUP'

LOGIN_SCREEN_KV = '../kv files/login_screen.kv'
MENU_SCREEN_KV = '../kv files/menu_screen.kv'
SIGNUP_SCREEN_KV = '../kv files/signup_screen.kv'

INVALID_TOKEN_CODE = 401
INVALID_CODE = 400
POST_SUCCESS_CODE = 201
GET_SUCCESS_CODE = 200
NOT_FOUND_CODE = 404
